#!/usr/bin/env python3
"""Generate endpoints/config.yml and the OpenHands profiles from .env.

    python3 scripts/config.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "openhands" / "state"

# role -> prompt file. coder-1 and coder-2 share a prompt; each owns one module.
ROLES = {
    "architect": "01-architect",
    "techlead": "02-tech-lead",
    "coder-1": "03-implementation",
    "coder-2": "03-implementation",
    "tester": "04-testing",
    "docs": "05-documentation",
    "deploy-validator": "06-deployment",
}
WORKER_MODULE = {"coder-1": "storage.py", "coder-2": "server.py"}


def load_env():
    env = {}
    for line in (ROOT / ".env").read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip()
    return env


def endpoint_of(role, env):
    for letter in ("A", "B"):
        if role in env[f"ENDPOINT_{letter}_ROLES"].split(","):
            return letter
    raise SystemExit(f"role {role} is not in ENDPOINT_A_ROLES or ENDPOINT_B_ROLES")


def config_yml(env):
    lines = ["# Generated by scripts/config.py from .env - do not edit.", "model_list:"]
    for role in ROLES:
        letter = endpoint_of(role, env)
        lines += [
            f"  - model_name: {role}",
            "    litellm_params:",
            f"      model: openai/{env[f'ENDPOINT_{letter}_MODEL']}",
            f"      api_base: http://host.docker.internal:{env[f'ENDPOINT_{letter}_PORT']}/v1",
            "      api_key: ollama",
            f"      max_tokens: {env['MAX_OUTPUT_TOKENS']}",
            "    model_info:",
            "      supports_function_calling: true",
            f"      max_input_tokens: {env['MAX_INPUT_TOKENS']}",
        ]
    lines += ["litellm_settings:", "  drop_params: true",
              f"  request_timeout: {env['LLM_TIMEOUT']}", ""]
    return "\n".join(lines)


def profiles(env):
    out = {}
    for role in ROLES:
        out[STATE / "profiles" / f"{role}.json"] = {
            "base_url": "http://litellm:4000",
            "auth_type": "api_key",
            # OpenHands does not expand env references here, so the key is literal.
            "api_key": env["LITELLM_MASTER_KEY"],
            "api_mode": "chat",
            "timeout": int(env["LLM_TIMEOUT"]),
            "model": f"openai/{role}",
            "native_tool_calling": True,
            "temperature": 0.0,
        }
        agent_path = STATE / "agent-profiles" / f"{role}.json"
        old = json.loads(agent_path.read_text()) if agent_path.exists() else {}
        out[agent_path] = {
            "schema_version": 2,
            # Keep the id OpenHands already knows this profile by.
            "id": old.get("id") or role,
            "name": role,
            "agent_kind": "openhands",
            "llm_profile_ref": role,
            "agent": "CodeActAgent",
            # Only what the roles use. The default adds 13 browser tools and
            # switch_llm, which every request re-sends and the model re-reads.
            "tools": [{"name": "terminal"}, {"name": "file_editor"}],
            "enable_switch_llm_tool": False,
            # Bundled skills are injected into every prompt unless denied here.
            "disabled_skills": env["DISABLED_SKILLS"].split(","),
        }
    return out


def sync():
    env = load_env()
    (ROOT / "endpoints" / "config.yml").write_text(config_yml(env))
    for path, data in profiles(env).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n")
    return env


if __name__ == "__main__":
    env = sync()
    for letter in ("A", "B"):
        print(f"endpoint {letter}: {env[f'ENDPOINT_{letter}_MODEL']} "
              f"on :{env[f'ENDPOINT_{letter}_PORT']} -> {env[f'ENDPOINT_{letter}_ROLES']}")
